import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Rogelio Cervantes Castellon
 */
public class FPrincipal extends javax.swing.JFrame {

    Conexion cnx = new Conexion();
    
    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    boolean checkPassword(String password) {
        Pattern letter = Pattern.compile("[a-zA-z]");
        Pattern digit = Pattern.compile("[0-9]");
        Pattern special = Pattern.compile ("[!@#$%&*()_+=|<>?{}\\[\\]~-]");
        Pattern upperCase = Pattern.compile("[A-Z]");
        Pattern lowerCase = Pattern.compile("[a-z]");

        Matcher hasLetter = letter.matcher(password);
        Matcher hasDigit = digit.matcher(password);
        Matcher hasSpecial = special.matcher(password);
        Matcher hasUpperCase = upperCase.matcher(password);
        Matcher hasLowerCase = lowerCase.matcher(password);

        boolean isPasswordValid = hasLetter.find() && hasDigit.find() && hasSpecial.find() && hasUpperCase.find() && hasLowerCase.find();
        
        return isPasswordValid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PAgregar = new javax.swing.JPanel();
        A_TFNombre = new javax.swing.JTextField();
        A_TFApellido = new javax.swing.JTextField();
        A_TFUser = new javax.swing.JTextField();
        A_Contraseña = new javax.swing.JPasswordField();
        A_BRegistrar = new javax.swing.JButton();
        PDatos = new javax.swing.JPanel();
        D_TFNombre = new javax.swing.JTextField();
        D_TFApellido = new javax.swing.JTextField();
        LDAlumno = new javax.swing.JLabel();
        LDPadre = new javax.swing.JLabel();
        D_TFNombreP = new javax.swing.JTextField();
        D_TFApellidoP = new javax.swing.JTextField();
        D_TFTelefonoP = new javax.swing.JTextField();
        LDPadre1 = new javax.swing.JLabel();
        D_TFNombreM = new javax.swing.JTextField();
        D_TFApellidoM = new javax.swing.JTextField();
        D_TFTelefonoM = new javax.swing.JTextField();
        D_BRegistrar = new javax.swing.JButton();
        LGrado = new javax.swing.JLabel();
        D_SGrado = new javax.swing.JSpinner();
        LEdad = new javax.swing.JLabel();
        D_SEdad = new javax.swing.JSpinner();
        LPromedio = new javax.swing.JLabel();
        D_SPromedio = new javax.swing.JSpinner();
        PConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDatosA = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDatosP = new javax.swing.JTable();
        C_BModificar = new javax.swing.JButton();
        C_BEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(29, 29, 29));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        PAgregar.setBackground(new java.awt.Color(29, 29, 29));
        PAgregar.setForeground(new java.awt.Color(255, 255, 255));

        A_TFNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre(s):", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        A_TFApellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TFApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        A_TFUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_TFUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de usuario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        A_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        A_Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        A_BRegistrar.setBackground(new java.awt.Color(239, 0, 62));
        A_BRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        A_BRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        A_BRegistrar.setText("Registrar");
        A_BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PAgregarLayout = new javax.swing.GroupLayout(PAgregar);
        PAgregar.setLayout(PAgregarLayout);
        PAgregarLayout.setHorizontalGroup(
            PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PAgregarLayout.createSequentialGroup()
                        .addComponent(A_TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A_TFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PAgregarLayout.createSequentialGroup()
                        .addComponent(A_TFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(A_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_BRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PAgregarLayout.setVerticalGroup(
            PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PAgregarLayout.createSequentialGroup()
                        .addGroup(PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A_TFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(A_TFApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_TFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(A_BRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", PAgregar);

        PDatos.setBackground(new java.awt.Color(29, 29, 29));
        PDatos.setForeground(new java.awt.Color(255, 255, 255));

        D_TFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre(s):", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_TFApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        LDAlumno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LDAlumno.setForeground(new java.awt.Color(255, 255, 255));
        LDAlumno.setText("Datos del alumno");
        LDAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        LDPadre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LDPadre.setForeground(new java.awt.Color(255, 255, 255));
        LDPadre.setText("Datos del padre");
        LDPadre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        D_TFNombreP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre(s):", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_TFApellidoP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_TFTelefonoP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        LDPadre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LDPadre1.setForeground(new java.awt.Color(255, 255, 255));
        LDPadre1.setText("Datos de la madre");
        LDPadre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        D_TFNombreM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre(s):", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_TFApellidoM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_TFTelefonoM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        D_BRegistrar.setBackground(new java.awt.Color(239, 0, 62));
        D_BRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        D_BRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        D_BRegistrar.setText("Registrar");
        D_BRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_BRegistrarActionPerformed(evt);
            }
        });

        LGrado.setBackground(new java.awt.Color(29, 29, 29));
        LGrado.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LGrado.setForeground(new java.awt.Color(255, 255, 255));
        LGrado.setText("Grado:");

        D_SGrado.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));

        LEdad.setBackground(new java.awt.Color(29, 29, 29));
        LEdad.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LEdad.setForeground(new java.awt.Color(255, 255, 255));
        LEdad.setText("Edad:");

        D_SEdad.setModel(new javax.swing.SpinnerNumberModel(6, 6, 12, 1));

        LPromedio.setBackground(new java.awt.Color(29, 29, 29));
        LPromedio.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LPromedio.setForeground(new java.awt.Color(255, 255, 255));
        LPromedio.setText("Promedio:");

        D_SPromedio.setModel(new javax.swing.SpinnerNumberModel(60, 60, 100, 1));

        javax.swing.GroupLayout PDatosLayout = new javax.swing.GroupLayout(PDatos);
        PDatos.setLayout(PDatosLayout);
        PDatosLayout.setHorizontalGroup(
            PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(D_TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_TFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LDAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(D_TFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_TFApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LDPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D_TFTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(D_TFNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_TFApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LDPadre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(D_TFTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_BRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LGrado)
                            .addComponent(D_SGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LEdad)
                            .addComponent(D_SEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPromedio)
                            .addComponent(D_SPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        PDatosLayout.setVerticalGroup(
            PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LDAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_TFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(LGrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_SGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(LEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_SEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PDatosLayout.createSequentialGroup()
                        .addComponent(LPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_SPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LDPadre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_TFNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_TFApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_TFTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LDPadre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_TFNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_TFApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_TFTelefonoM, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_BRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos", PDatos);

        PConsultar.setBackground(new java.awt.Color(29, 29, 29));
        PConsultar.setForeground(new java.awt.Color(255, 255, 255));

        TDatosA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TDatosA);

        TDatosP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TDatosP);

        C_BModificar.setBackground(new java.awt.Color(239, 0, 62));
        C_BModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        C_BModificar.setForeground(new java.awt.Color(255, 255, 255));
        C_BModificar.setText("Modificar");

        C_BEliminar.setBackground(new java.awt.Color(239, 0, 62));
        C_BEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        C_BEliminar.setForeground(new java.awt.Color(255, 255, 255));
        C_BEliminar.setText("Eliminar");

        javax.swing.GroupLayout PConsultarLayout = new javax.swing.GroupLayout(PConsultar);
        PConsultar.setLayout(PConsultarLayout);
        PConsultarLayout.setHorizontalGroup(
            PConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PConsultarLayout.createSequentialGroup()
                        .addComponent(C_BModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C_BEliminar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PConsultarLayout.setVerticalGroup(
            PConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_BModificar)
                    .addComponent(C_BEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar", PConsultar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BRegistrarActionPerformed
        String nombre = A_TFNombre.getText() + " " + A_TFApellido.getText();
        String usuario = A_TFUser.getText();
        String contrasena = A_Contraseña.getText();
        
        if (A_TFNombre.getText().equals("") || A_TFApellido.getText().equals("") || usuario.equals("") || contrasena.equals("")) {
            JOptionPane.showMessageDialog(null, "Asegurate de llenar correctamente todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else if (!checkPassword(contrasena) && contrasena.length() < 10) {
            JOptionPane.showMessageDialog(null, "Contraseña inválida.La contraseña debe de contener al menos \nuna letra mayúscula, una letra minúscula, un número y un símbolo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            Usuarios user = new Usuarios(nombre, usuario, contrasena);
            if (user.insertar(cnx) == 1) {
                JOptionPane.showMessageDialog(null, "Registro exitoso.", "Registro", JOptionPane.INFORMATION_MESSAGE);
                A_TFNombre.setText("");
                A_TFApellido.setText("");
                A_TFUser.setText("");
                A_Contraseña.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Registro fallido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_A_BRegistrarActionPerformed

    private void D_BRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_BRegistrarActionPerformed
        String nombre = D_TFNombre.getText() + " " + D_TFApellido.getText();
        int grado = Integer.parseInt(D_SGrado.getValue().toString());
        int edad = Integer.parseInt(D_SEdad.getValue().toString());
        int promedio = Integer.parseInt(D_SPromedio.getValue().toString());
        String nombrePapa = D_TFNombreP.getText() + " " + D_TFApellidoP.getText();
        String telefonoPapa = D_TFTelefonoP.getText();
        String nombreMama = D_TFNombreM.getText() + " " + D_TFApellidoM.getText();
        String telefonoMama = D_TFTelefonoM.getText();
        
        if (D_TFNombre.getText().equals("") || D_TFApellido.getText().equals("") || 
                D_TFNombreP.getText().equals("") || D_TFApellidoP.getText().equals("") ||
                D_TFNombreM.getText().equals("") || D_TFApellidoM.getText().equals("") ||
                telefonoPapa.equals("") || telefonoMama.equals("")) {
            JOptionPane.showMessageDialog(null, "Asegurate de llenar correctamente todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            Alumnos alum = new Alumnos(nombre, grado, edad, promedio, nombrePapa, telefonoPapa, nombreMama, telefonoMama);
            if (alum.insertar(cnx) == 1) {
                JOptionPane.showMessageDialog(null, "Registro exitoso.", "Registro", JOptionPane.INFORMATION_MESSAGE);
                D_TFNombre.setText("");
                D_TFApellido.setText("");
                D_TFNombreP.setText("");
                D_TFApellidoP.setText("");
                D_TFTelefonoP.setText("");
                D_TFNombreM.setText("");
                D_TFApellidoM.setText("");
                D_TFTelefonoM.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Registro fallido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_D_BRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BRegistrar;
    private javax.swing.JPasswordField A_Contraseña;
    private javax.swing.JTextField A_TFApellido;
    private javax.swing.JTextField A_TFNombre;
    private javax.swing.JTextField A_TFUser;
    private javax.swing.JButton C_BEliminar;
    private javax.swing.JButton C_BModificar;
    private javax.swing.JButton D_BRegistrar;
    private javax.swing.JSpinner D_SEdad;
    private javax.swing.JSpinner D_SGrado;
    private javax.swing.JSpinner D_SPromedio;
    private javax.swing.JTextField D_TFApellido;
    private javax.swing.JTextField D_TFApellidoM;
    private javax.swing.JTextField D_TFApellidoP;
    private javax.swing.JTextField D_TFNombre;
    private javax.swing.JTextField D_TFNombreM;
    private javax.swing.JTextField D_TFNombreP;
    private javax.swing.JTextField D_TFTelefonoM;
    private javax.swing.JTextField D_TFTelefonoP;
    private javax.swing.JLabel LDAlumno;
    private javax.swing.JLabel LDPadre;
    private javax.swing.JLabel LDPadre1;
    private javax.swing.JLabel LEdad;
    private javax.swing.JLabel LGrado;
    private javax.swing.JLabel LPromedio;
    private javax.swing.JPanel PAgregar;
    private javax.swing.JPanel PConsultar;
    private javax.swing.JPanel PDatos;
    private javax.swing.JTable TDatosA;
    private javax.swing.JTable TDatosP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
