
import javax.swing.ImageIcon;
/**
 *
 * @author thero
 */
public class FInicio extends javax.swing.JFrame {
    
    ImageIcon icon = new ImageIcon(getClass().getResource("/img/icons/voidcat_logo.png"));
    
    public FInicio() {
        initComponents();
        setIconImage(icon.getImage());
        setTitle("Memorama - Inicio");
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LEncabezado = new javax.swing.JLabel();
        LFacil_I = new javax.swing.JLabel();
        LMedio_I = new javax.swing.JLabel();
        LDificil_I = new javax.swing.JLabel();
        LFacil_T = new javax.swing.JLabel();
        LMedio_T = new javax.swing.JLabel();
        LDificil_T = new javax.swing.JLabel();
        LInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(29, 29, 29));

        LEncabezado.setBackground(new java.awt.Color(239, 0, 62));
        LEncabezado.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        LEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LEncabezado.setText("Conceptos básicos - Memorama");
        LEncabezado.setOpaque(true);

        LFacil_I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LFacil_I.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/facil.png"))); // NOI18N
        LFacil_I.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LFacil_I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LFacil_IMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LFacil_IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LFacil_IMouseExited(evt);
            }
        });

        LMedio_I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LMedio_I.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/medio.png"))); // NOI18N
        LMedio_I.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LMedio_I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMedio_IMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LMedio_IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LMedio_IMouseExited(evt);
            }
        });

        LDificil_I.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LDificil_I.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons/dificil.png"))); // NOI18N
        LDificil_I.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LDificil_I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LDificil_IMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LDificil_IMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LDificil_IMouseExited(evt);
            }
        });

        LFacil_T.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LFacil_T.setForeground(new java.awt.Color(255, 255, 255));
        LFacil_T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LFacil_T.setText("Fácil");

        LMedio_T.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LMedio_T.setForeground(new java.awt.Color(255, 255, 255));
        LMedio_T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LMedio_T.setText("Medio");

        LDificil_T.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LDificil_T.setForeground(new java.awt.Color(255, 255, 255));
        LDificil_T.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LDificil_T.setText("Dificil");

        LInstrucciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        LInstrucciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LInstrucciones.setText("Haz click en la imagen para escoger la dificultad");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LFacil_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LFacil_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LMedio_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LMedio_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LDificil_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDificil_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LInstrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(LEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LInstrucciones)
                .addGap(41, 41, 41)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LFacil_T)
                    .addComponent(LMedio_T)
                    .addComponent(LDificil_T))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LMedio_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LDificil_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LFacil_I, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LFacil_IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LFacil_IMouseEntered
        LFacil_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/facil2.png")));
    }//GEN-LAST:event_LFacil_IMouseEntered

    private void LFacil_IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LFacil_IMouseExited
        LFacil_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/facil.png")));
    }//GEN-LAST:event_LFacil_IMouseExited

    private void LFacil_IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LFacil_IMouseClicked
        FFacil facil = new FFacil();
        facil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LFacil_IMouseClicked

    private void LMedio_IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMedio_IMouseEntered
        LMedio_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/medio2.png")));
    }//GEN-LAST:event_LMedio_IMouseEntered

    private void LMedio_IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMedio_IMouseExited
        LMedio_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/medio.png")));
    }//GEN-LAST:event_LMedio_IMouseExited

    private void LMedio_IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMedio_IMouseClicked
        FMedio medio = new FMedio();
        medio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LMedio_IMouseClicked

    private void LDificil_IMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDificil_IMouseEntered
        LDificil_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/dificil2.png")));
    }//GEN-LAST:event_LDificil_IMouseEntered

    private void LDificil_IMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDificil_IMouseExited
        LDificil_I.setIcon(new ImageIcon(getClass().getResource("/img/icons/dificil.png")));
    }//GEN-LAST:event_LDificil_IMouseExited

    private void LDificil_IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LDificil_IMouseClicked
        FDificil dificil = new FDificil();
        dificil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LDificil_IMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LDificil_I;
    private javax.swing.JLabel LDificil_T;
    private javax.swing.JLabel LEncabezado;
    private javax.swing.JLabel LFacil_I;
    private javax.swing.JLabel LFacil_T;
    private javax.swing.JLabel LInstrucciones;
    private javax.swing.JLabel LMedio_I;
    private javax.swing.JLabel LMedio_T;
    // End of variables declaration//GEN-END:variables
}
