
import java.security.SecureRandom;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thero
 */
public class FVentana extends javax.swing.JFrame {

    Archivo archivoDeTexto = new Archivo();
    ArrayList<JTextField> tfArr = new ArrayList();
    DefaultTableModel modeloTabla;
    String[] tableHeaders = {"Nombre", "Apellido P", "Apellido M"};
    String[] datosFormulario = new String[10];
    SecureRandom randNum = new SecureRandom();
    ImageIcon icon = new ImageIcon(getClass().getResource("/img/voidcat_logo.png"));

    public FVentana() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Crear archivos de texto");
        setIconImage(icon.getImage());
        inicializarTabla();
        cargarObjetos();
        onOff(false);
        cargarTabla();
    }

    void cargarObjetos() {
        tfArr.add(TFCodigo);
        tfArr.add(TFNombre);
        tfArr.add(TFApellidoP);
        tfArr.add(TFApellidoM);
        tfArr.add(TFEdad);
        tfArr.add(TFDomicilio);
        tfArr.add(TFMunicipio);
        tfArr.add(TFCP);
    }

    void onOff(boolean actDes) {
        for (int i = 0; i < tfArr.size(); i++) {
            if (i == 0) {
                tfArr.get(i).setEnabled(false);
            } else {
                tfArr.get(i).setEnabled(actDes);
            }
        }
        CBEstadoCivil.setEnabled(actDes);
        CBSexo.setEnabled(actDes);
    }

    void cargarTabla() {
        String[] nombresArchivosGuardados = archivoDeTexto.nombreRegistros();

        for (int i = 0; i < nombresArchivosGuardados.length; i++) {
            modeloTabla.addRow(archivoDeTexto.leerRegistro(nombresArchivosGuardados[i]));
            TTabla.setModel(modeloTabla);
        }
    }

    void inicializarTabla() {
        modeloTabla = new DefaultTableModel(null, tableHeaders);
        TTabla.setModel(modeloTabla);
    }

    String codigoAleatorio() {
        return "" + randNum.nextInt(999999);
    }

    void limpiarCampos() {
        int x = 0;
        for (int i = 0; i < 10; i++) {
            switch (i) {
                case 5:
                    CBSexo.setSelectedIndex(0);
                    break;
                case 6:
                    CBEstadoCivil.setSelectedIndex(0);
                    break;
                default:
                    tfArr.get(x).setText("");
                    x++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PBackground = new javax.swing.JPanel();
        LEncabezado = new javax.swing.JLabel();
        PInfo = new javax.swing.JPanel();
        CBSexo = new javax.swing.JComboBox<>();
        BCancelar = new javax.swing.JButton();
        CBEstadoCivil = new javax.swing.JComboBox<>();
        TFDomicilio = new javax.swing.JTextField();
        TFMunicipio = new javax.swing.JTextField();
        TFCodigo = new javax.swing.JTextField();
        TFNombre = new javax.swing.JTextField();
        TFApellidoP = new javax.swing.JTextField();
        TFCP = new javax.swing.JTextField();
        TFApellidoM = new javax.swing.JTextField();
        BGuardar = new javax.swing.JButton();
        TFEdad = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TTabla = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 29, 29));

        PBackground.setBackground(new java.awt.Color(29, 29, 29));
        PBackground.setForeground(new java.awt.Color(255, 255, 255));

        LEncabezado.setBackground(new java.awt.Color(239, 0, 62));
        LEncabezado.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        LEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        LEncabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LEncabezado.setText("Registro de alumnos");
        LEncabezado.setOpaque(true);

        PInfo.setBackground(new java.awt.Color(29, 29, 29));
        PInfo.setLayout(null);

        CBSexo.setBackground(new java.awt.Color(85, 85, 85));
        CBSexo.setForeground(new java.awt.Color(220, 220, 220));
        CBSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Hombre", "Mujer" }));
        CBSexo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        PInfo.add(CBSexo);
        CBSexo.setBounds(10, 70, 92, 48);

        BCancelar.setBackground(new java.awt.Color(239, 0, 62));
        BCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BCancelar.setForeground(new java.awt.Color(220, 220, 220));
        BCancelar.setText("Cancelar");
        BCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelarActionPerformed(evt);
            }
        });
        PInfo.add(BCancelar);
        BCancelar.setBounds(120, 130, 100, 27);

        CBEstadoCivil.setBackground(new java.awt.Color(85, 85, 85));
        CBEstadoCivil.setForeground(new java.awt.Color(220, 220, 220));
        CBEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Soltero", "Casado", "Viudo", "Divorciado" }));
        CBEstadoCivil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado civil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        PInfo.add(CBEstadoCivil);
        CBEstadoCivil.setBounds(120, 70, 160, 48);

        TFDomicilio.setBackground(new java.awt.Color(39, 39, 39));
        TFDomicilio.setForeground(new java.awt.Color(220, 220, 220));
        TFDomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFDomicilio.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFDomicilio);
        TFDomicilio.setBounds(300, 70, 192, 48);

        TFMunicipio.setBackground(new java.awt.Color(39, 39, 39));
        TFMunicipio.setForeground(new java.awt.Color(220, 220, 220));
        TFMunicipio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Municipio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFMunicipio.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFMunicipio);
        TFMunicipio.setBounds(510, 70, 160, 48);

        TFCodigo.setBackground(new java.awt.Color(39, 39, 39));
        TFCodigo.setForeground(new java.awt.Color(220, 220, 220));
        TFCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFCodigo.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFCodigo);
        TFCodigo.setBounds(10, 10, 92, 48);

        TFNombre.setBackground(new java.awt.Color(39, 39, 39));
        TFNombre.setForeground(new java.awt.Color(220, 220, 220));
        TFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre(s)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFNombre.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFNombre);
        TFNombre.setBounds(120, 10, 192, 48);

        TFApellidoP.setBackground(new java.awt.Color(39, 39, 39));
        TFApellidoP.setForeground(new java.awt.Color(220, 220, 220));
        TFApellidoP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido paterno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFApellidoP.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFApellidoP);
        TFApellidoP.setBounds(330, 10, 160, 48);

        TFCP.setBackground(new java.awt.Color(39, 39, 39));
        TFCP.setForeground(new java.awt.Color(220, 220, 220));
        TFCP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código postal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFCP.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFCP);
        TFCP.setBounds(680, 70, 92, 48);

        TFApellidoM.setBackground(new java.awt.Color(39, 39, 39));
        TFApellidoM.setForeground(new java.awt.Color(220, 220, 220));
        TFApellidoM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido materno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFApellidoM.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFApellidoM);
        TFApellidoM.setBounds(510, 10, 160, 48);

        BGuardar.setBackground(new java.awt.Color(239, 0, 62));
        BGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BGuardar.setForeground(new java.awt.Color(220, 220, 220));
        BGuardar.setText("Nuevo");
        BGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGuardarActionPerformed(evt);
            }
        });
        PInfo.add(BGuardar);
        BGuardar.setBounds(10, 130, 100, 27);

        TFEdad.setBackground(new java.awt.Color(39, 39, 39));
        TFEdad.setForeground(new java.awt.Color(220, 220, 220));
        TFEdad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(220, 220, 220))); // NOI18N
        TFEdad.setCaretColor(new java.awt.Color(220, 220, 220));
        PInfo.add(TFEdad);
        TFEdad.setBounds(680, 10, 92, 48);

        TTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TTabla);

        javax.swing.GroupLayout PBackgroundLayout = new javax.swing.GroupLayout(PBackground);
        PBackground.setLayout(PBackgroundLayout);
        PBackgroundLayout.setHorizontalGroup(
            PBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(PInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PBackgroundLayout.setVerticalGroup(
            PBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBackgroundLayout.createSequentialGroup()
                .addComponent(LEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGuardarActionPerformed
        if (BGuardar.getText().equals("Registrar")) {
            int x = 0;
            for (int i = 0; i < 10; i++) {
                switch (i) {
                    case 5:
                        datosFormulario[i] = CBSexo.getSelectedItem().toString();
                        break;
                    case 6:
                        datosFormulario[i] = CBEstadoCivil.getSelectedItem().toString();
                        break;
                    default:
                        datosFormulario[i] = tfArr.get(x).getText();
                        x++;
                }
            }
            archivoDeTexto.guardarRegistro(datosFormulario, datosFormulario[0]);
            inicializarTabla();
            cargarTabla();
            BGuardar.setText("Nuevo");
            limpiarCampos();
            onOff(false);
        } else {
            BGuardar.setText("Registrar");
            onOff(true);
            tfArr.get(0).setText(codigoAleatorio());
        }
    }//GEN-LAST:event_BGuardarActionPerformed

    private void BCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelarActionPerformed
        limpiarCampos();
        BGuardar.setText("Nuevo");
        onOff(false);
    }//GEN-LAST:event_BCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCancelar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JComboBox<String> CBEstadoCivil;
    private javax.swing.JComboBox<String> CBSexo;
    private javax.swing.JLabel LEncabezado;
    private javax.swing.JPanel PBackground;
    private javax.swing.JPanel PInfo;
    private javax.swing.JTextField TFApellidoM;
    private javax.swing.JTextField TFApellidoP;
    private javax.swing.JTextField TFCP;
    private javax.swing.JTextField TFCodigo;
    private javax.swing.JTextField TFDomicilio;
    private javax.swing.JTextField TFEdad;
    private javax.swing.JTextField TFMunicipio;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTable TTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
