
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

// @author Rogelio Cervantes Castellon
public class FVentana extends javax.swing.JFrame {

    Registro[] registros = new Registro[4];
    JTextField[] registroTF = new JTextField[5];
    JButton[] botones = new JButton[4];
    Color rojizo = new Color(239, 0, 62);
    Color grisaceo = new Color(29, 29, 29);

    enum E {
        LIBRE, OCUPADO, SELECCIONADO
    }
    int numeroEtiqueta;

    public FVentana() {
        initComponents();
        setLocationRelativeTo(this);
        cargarElementos();
        onOff(false);
        TFRegistro.setEnabled(false);
    }

    void cargarElementos() {
        registros[0] = new Registro(LR1, false, new String[5]);
        registros[1] = new Registro(LR2, false, new String[5]);
        registros[2] = new Registro(LR3, false, new String[5]);
        registros[3] = new Registro(LR4, false, new String[5]);

        registroTF[0] = TFRegistro;
        registroTF[1] = TFNombre;
        registroTF[2] = TFTelefono;
        registroTF[3] = TFSangre;
        registroTF[4] = TFEdad;

        botones[0] = BNuevo;
        botones[1] = BModificar;
        botones[2] = BEliminar;
        botones[3] = BLimpiar;
    }

    void onOff(boolean actDesc) {
        for (int y = 1; y < registroTF.length; y++) {
            registroTF[y].setEnabled(actDesc);
        }

        for (int z = 0; z < botones.length; z++) {
            botones[z].setEnabled(actDesc);
        }
    }

    void coloresFondo(E estado) {
        switch (estado) {
            case LIBRE:
                registros[numeroEtiqueta].getEtiqueta().setBackground(Color.WHITE);
                registros[numeroEtiqueta].getEtiqueta().setForeground(grisaceo);
                break;
            case OCUPADO:
                registros[numeroEtiqueta].getEtiqueta().setBackground(grisaceo);
                registros[numeroEtiqueta].getEtiqueta().setForeground(Color.WHITE);
                break;
            case SELECCIONADO:
                registros[numeroEtiqueta].getEtiqueta().setBackground(rojizo);
                registros[numeroEtiqueta].getEtiqueta().setForeground(grisaceo);
                break;
            default:
                throw new AssertionError();
        }
    }

    void limpiar() {
        for (int i = 0; i < registroTF.length; i++) {
            registroTF[i].setText("");
        }
    }

    void etiquetaSeleccionada() {
        if (registros[numeroEtiqueta].getEtiqueta().getBackground() != rojizo) {
            if (registros[numeroEtiqueta].isOcupado()) {
                for (int i = 0; i < registroTF.length; i++) {
                    registroTF[i].setText(registros[numeroEtiqueta].getDatos()[i]);
                }
                BModificar.setEnabled(true);
                BEliminar.setEnabled(true);
            } else {
                BNuevo.setEnabled(true);
                coloresFondo(E.SELECCIONADO);
            }
        }
    }

    boolean checkInfo() {
        String[] tipoSangre = {"A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"};
        String telefono = TFTelefono.getText();
        String edad = TFEdad.getText();
        boolean[] boolArr = {true, true, true, true, true};

        for (int i = 0; i < tipoSangre.length; i++) {
            if (tipoSangre[i].equals(TFSangre.getText())) {
                boolArr[0] = true;
                break;
            } else {
                boolArr[0] = false;
            }
        }

        for (int i = 0; i < registroTF.length; i++) {
            if (registroTF[i].getText().equals("")) {
                boolArr[1] = false;
                break;
            }
        }

        for (int i = 0; i < telefono.length(); i++) {
            if (!Character.isDigit(telefono.charAt(i))) {
                boolArr[2] = false;
                break;
            }
        }

        for (int i = 0; i < edad.length(); i++) {
            if (!Character.isDigit(edad.charAt(i))) {
                boolArr[3] = false;
                break;
            }
        }

        if (telefono.length() != 10) {
            boolArr[4] = false;
        }

        return (boolArr[0] && boolArr[1] && boolArr[2] && boolArr[3] && boolArr[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LR1 = new javax.swing.JLabel();
        LR2 = new javax.swing.JLabel();
        LR3 = new javax.swing.JLabel();
        LR4 = new javax.swing.JLabel();
        TFRegistro = new javax.swing.JTextField();
        TFSangre = new javax.swing.JTextField();
        TFEdad = new javax.swing.JTextField();
        BNuevo = new javax.swing.JButton();
        BModificar = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();
        TFNombre = new javax.swing.JTextField();
        BLimpiar = new javax.swing.JButton();
        TFTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LR1.setBackground(new java.awt.Color(255, 255, 255));
        LR1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LR1.setForeground(new java.awt.Color(29, 29, 29));
        LR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LR1.setText("R1");
        LR1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LR1.setOpaque(true);
        LR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LR1MouseClicked(evt);
            }
        });

        LR2.setBackground(new java.awt.Color(255, 255, 255));
        LR2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LR2.setForeground(new java.awt.Color(29, 29, 29));
        LR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LR2.setText("R2");
        LR2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LR2.setOpaque(true);
        LR2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LR2MouseClicked(evt);
            }
        });

        LR3.setBackground(new java.awt.Color(255, 255, 255));
        LR3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LR3.setForeground(new java.awt.Color(29, 29, 29));
        LR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LR3.setText("R3");
        LR3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LR3.setOpaque(true);
        LR3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LR3MouseClicked(evt);
            }
        });

        LR4.setBackground(new java.awt.Color(255, 255, 255));
        LR4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LR4.setForeground(new java.awt.Color(29, 29, 29));
        LR4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LR4.setText("R4");
        LR4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LR4.setOpaque(true);
        LR4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LR4MouseClicked(evt);
            }
        });

        TFRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        TFSangre.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de sangre"));

        TFEdad.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));

        BNuevo.setText("Nuevo");
        BNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNuevoActionPerformed(evt);
            }
        });

        BModificar.setText("Modificar");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        TFNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        BLimpiar.setText("Limpiar");

        TFTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LR1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LR2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LR3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LR4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LR1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LR2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LR3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LR4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BNuevo)
                            .addComponent(BModificar)
                            .addComponent(BEliminar)
                            .addComponent(BLimpiar))))
                .addGap(224, 224, 224))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LR1MouseClicked
        numeroEtiqueta = 0;
        etiquetaSeleccionada();
    }//GEN-LAST:event_LR1MouseClicked

    private void LR2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LR2MouseClicked
        numeroEtiqueta = 1;
        etiquetaSeleccionada();
    }//GEN-LAST:event_LR2MouseClicked

    private void LR3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LR3MouseClicked
        numeroEtiqueta = 2;
        etiquetaSeleccionada();
    }//GEN-LAST:event_LR3MouseClicked

    private void LR4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LR4MouseClicked
        numeroEtiqueta = 3;
        etiquetaSeleccionada();
    }//GEN-LAST:event_LR4MouseClicked

    private void BNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNuevoActionPerformed
        if (BNuevo.getText().equals("Nuevo")) {
            onOff(true);
            BNuevo.setText("Guardar");
            BEliminar.setText("Cancelar");
            TFRegistro.setText(registros[numeroEtiqueta].getEtiqueta().getText());
            TFNombre.requestFocus();
        } else {
            if (!checkInfo()) {
                JOptionPane.showMessageDialog(null, "Uno de los campos es incorrecto.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                for (int x = 0; x < registros[numeroEtiqueta].getDatos().length; x++) {
                    registros[numeroEtiqueta].getDatos()[x] = registroTF[x].getText();
                }
                registros[numeroEtiqueta].setOcupado(true);
                coloresFondo(E.OCUPADO);
                limpiar();
                onOff(false);
                BNuevo.setText("Nuevo");
                BEliminar.setText("Eliminar");
            }
        }
    }//GEN-LAST:event_BNuevoActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        if (BEliminar.getText().equals("Eliminar")) {
            if (JOptionPane.showConfirmDialog(null, "¿Seguro?", "Eliminar registro", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)
                    == JOptionPane.YES_OPTION) {
                registros[numeroEtiqueta].setDatos(null);
                registros[numeroEtiqueta].setOcupado(false);
                limpiar();
                onOff(false);
                coloresFondo(E.LIBRE);
            }
        } else {
            limpiar();
            onOff(false);
            coloresFondo(E.LIBRE);
            BNuevo.setText("Nuevo");
            BEliminar.setText("Eliminar");
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Cupertino Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton BModificar;
    private javax.swing.JButton BNuevo;
    private javax.swing.JLabel LR1;
    private javax.swing.JLabel LR2;
    private javax.swing.JLabel LR3;
    private javax.swing.JLabel LR4;
    private javax.swing.JTextField TFEdad;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFRegistro;
    private javax.swing.JTextField TFSangre;
    private javax.swing.JTextField TFTelefono;
    // End of variables declaration//GEN-END:variables
}
